# -*- coding: utf-8 -*-
"""streamlit_app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VR_jEDY2cvkOmQNU3m5hkCnr3WDNklPo
"""

import streamlit as st
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import io
from t_utils import (
    generate_constellation_tle,
    create_constellation_plots,
    generate_tle_file_content,
    create_validation_report
)

# Password protection
def check_password():
    """Returns True if password is correct"""

    def password_entered():
        """Checks whether a password entered by the user is correct."""
        if st.session_state["password"] == "SUN2025":  # Change this password
            st.session_state["password_correct"] = True
            del st.session_state["password"]  # Don't store password
        else:
            st.session_state["password_correct"] = False

    if "password_correct" not in st.session_state:
        # First run, show input for password
        st.markdown("### 🛰️ TLE Constellation Generator")
        st.markdown("Enter password to access the application:")
        st.text_input(
            "Password",
            type="password",
            on_change=password_entered,
            key="password"
        )

        st.info("💡 **For team members**: Contact admin for access password")
        return False

    elif not st.session_state["password_correct"]:
        # Password not correct, show input + error
        st.markdown("### 🛰️ TLE Constellation Generator")
        st.text_input(
            "Password",
            type="password",
            on_change=password_entered,
            key="password"
        )
        st.error("😞 Password incorrect. Please try again.")
        return False

    else:
        # Password correct
        return True

def main():
    """Main application"""

    # Check password first
    if not check_password():
        return

    # App header
    st.set_page_config(
        page_title="TLE Constellation Generator",
        page_icon="🛰️",
        layout="wide",
        initial_sidebar_state="expanded"
    )

    st.title("🛰️ TLE Constellation Generator")
    st.markdown("Generate Two-Line Element (TLE) files for Walker satellite constellations")

    # Sidebar for parameters
    st.sidebar.header("Constellation Parameters")

    # Input widgets
    altitude = st.sidebar.slider(
        "Altitude (km)",
        min_value=200,
        max_value=2000,
        value=650,
        step=10,
        help="Satellite orbital altitude above Earth's surface"
    )

    inclination = st.sidebar.slider(
        "Inclination (degrees)",
        min_value=0.0,
        max_value=180.0,
        value=31.0,
        step=0.1,
        help="Orbital inclination angle"
    )

    num_planes = st.sidebar.number_input(
        "Number of Orbital Planes",
        min_value=1,
        max_value=500,
        value=317,
        step=1,
        help="Total number of orbital planes in the constellation"
    )

    sats_per_plane = st.sidebar.number_input(
        "Satellites per Plane",
        min_value=1,
        max_value=50,
        value=2,
        step=1,
        help="Number of satellites in each orbital plane"
    )

    walker_F = st.sidebar.number_input(
        "Walker F Parameter",
        min_value=0,
        max_value=1000,
        value=137,
        step=1,
        help="Walker constellation phasing factor"
    )

    # Generate button
    if st.sidebar.button("🚀 Generate Constellation", type="primary"):
        st.session_state.generate_constellation = True

    # Information section
    with st.sidebar.expander("ℹ️ About Walker Constellations"):
        st.markdown("""
        **Walker constellations** are characterized by three parameters:
        - **T**: Total number of satellites
        - **P**: Number of orbital planes
        - **F**: Phasing factor

        The notation is T/P/F (e.g., 634/317/137)

        **Key Features:**
        - Even satellite distribution
        - Optimized global coverage
        - Reduced coverage gaps
        """)

    # Main content area
    if hasattr(st.session_state, 'generate_constellation') and st.session_state.generate_constellation:

        # Calculate total satellites
        total_sats = num_planes * sats_per_plane

        # Show constellation info
        col1, col2, col3, col4 = st.columns(4)
        with col1:
            st.metric("Total Satellites", total_sats)
        with col2:
            st.metric("Orbital Planes", num_planes)
        with col3:
            st.metric("Walker Notation", f"{total_sats}/{num_planes}/{walker_F}")
        with col4:
            orbital_period = 2 * np.pi * np.sqrt((6378.137 + altitude)**3 / 398600.4418) / 60
            st.metric("Orbital Period", f"{orbital_period:.1f} min")

        # Generate constellation
        with st.spinner("Generating constellation TLE data..."):
            try:
                tle_lines, constellation_data = generate_constellation_tle(
                    altitude, inclination, num_planes, sats_per_plane, walker_F
                )

                # Create tabs for different outputs
                tab1, tab2, tab3, tab4 = st.tabs(["📊 Visualization", "📄 TLE Data", "📋 Report", "📈 Statistics"])

                with tab1:
                    st.subheader("Constellation Visualization")

                    # Generate and display plots
                    fig = create_constellation_plots(constellation_data)
                    st.pyplot(fig)

                    # Download plot
                    buf = io.BytesIO()
                    fig.savefig(buf, format='png', dpi=300, bbox_inches='tight')
                    buf.seek(0)
                    st.download_button(
                        label="📥 Download Plots (PNG)",
                        data=buf.getvalue(),
                        file_name=f"constellation_{total_sats}_{num_planes}_{walker_F}_plots.png",
                        mime="image/png"
                    )

                with tab2:
                    st.subheader("Generated TLE Data")

                    # Show first few TLE entries as preview
                    st.markdown("**Preview (first 5 satellites):**")
                    preview_lines = tle_lines[:15]  # 5 satellites * 3 lines each
                    st.code('\n'.join(preview_lines), language='text')

                    # Download TLE file
                    tle_content = generate_tle_file_content(tle_lines)
                    st.download_button(
                        label="📥 Download Complete TLE File",
                        data=tle_content,
                        file_name=f"kuiper_constellation_{total_sats}sats.tle",
                        mime="text/plain"
                    )

                    st.info(f"📊 Generated {total_sats} satellites across {num_planes} orbital planes")

                with tab3:
                    st.subheader("Validation Report")

                    report = create_validation_report(constellation_data)
                    st.text(report)

                    # Download report
                    st.download_button(
                        label="📥 Download Report (TXT)",
                        data=report,
                        file_name=f"constellation_report_{total_sats}_{num_planes}_{walker_F}.txt",
                        mime="text/plain"
                    )

                with tab4:
                    st.subheader("Satellite Statistics")

                    # Create DataFrame from satellite data
                    df = pd.DataFrame(constellation_data['satellite_data'])

                    col1, col2 = st.columns(2)

                    with col1:
                        st.markdown("**RAAN Distribution:**")
                        raan_stats = df['raan'].describe()
                        st.dataframe(raan_stats)

                        st.markdown("**Mean Anomaly Distribution:**")
                        ma_stats = df['mean_anomaly'].describe()
                        st.dataframe(ma_stats)

                    with col2:
                        st.markdown("**Satellites by Plane:**")
                        plane_counts = df['plane'].value_counts().sort_index()
                        st.dataframe(plane_counts.head(10))

                        st.markdown("**Sample Satellite Data:**")
                        st.dataframe(df[['name', 'plane', 'norad_id', 'raan', 'mean_anomaly']].head(10))

                    # Full data download
                    csv_data = df.to_csv(index=False)
                    st.download_button(
                        label="📥 Download Full Satellite Data (CSV)",
                        data=csv_data,
                        file_name=f"satellite_data_{total_sats}_{num_planes}_{walker_F}.csv",
                        mime="text/csv"
                    )

            except Exception as e:
                st.error(f"Error generating constellation: {str(e)}")
                st.exception(e)

    else:
        # Landing page
        st.markdown("""
        ### Welcome to the TLE Constellation Generator! 🛰️

        This tool generates **Two-Line Element (TLE)** files for Walker satellite constellations,
        designed to be compatible with **NCAT (Network Coverage Analysis Tool)** and other orbital analysis software.

        #### Key Features:
        - 🎯 **Randomized NORAD IDs** - No duplicate satellite identifiers
        - 🚀 **Diverse Launch Info** - Realistic launch years, numbers, and pieces
        - 📊 **Interactive Visualizations** - RAAN/MA distribution and ground track patterns
        - 📄 **Multiple Export Formats** - TLE files, reports, and CSV data
        - ✅ **NCAT Compatible** - Proper formatting with CR+LF line endings

        #### How to Use:
        1. **Adjust parameters** in the sidebar (altitude, inclination, planes, etc.)
        2. **Click "Generate Constellation"** to create your TLE data
        3. **Explore results** in the visualization and data tabs
        4. **Download files** for use in NCAT or other tools

        #### Parameter Guidelines:
        - **Altitude**: 200-2000 km (650 km is typical for LEO constellations)
        - **Inclination**: 0-180° (31° provides good global coverage)
        - **Planes**: More planes = better coverage but higher complexity
        - **Sats per plane**: Balance between coverage and cost
        - **Walker F**: Phasing factor for optimal satellite distribution

        **Ready to start?** Adjust the parameters in the sidebar and click Generate! 🚀
        """)

        # Add some example constellations
        st.markdown("### Example Configurations:")

        col1, col2 = st.columns(2)


        with col1:
            st.info("""
            **Starlink-like**
            📊 1584/72/22
            ✈️ 550 km altitude
            📐 53° inclination
            """)

        with col2:
            st.info("""
            **Small Test**
            📊 24/12/5
            ✈️ 500 km altitude
            📐 45° inclination
            """)

if __name__ == "__main__":
    main()